import "./globals.css";
import Header from "@/components/ui/header";
import Footer from "@/components/ui/footer";
import SmoothScroll from "@/components/smoothScroll";
import Providers from "./Provider";
import localFont from "next/font/local";

const raleway = localFont({
  src: [
    {
      path: "../../public/fonts/Railway/Raleway-Light.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../../public/fonts/Railway/Raleway-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/Railway/Raleway-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/fonts/Railway/Raleway-SemiBold.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../../public/fonts/Railway/Raleway-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-raleway",
});

const playfairDisplay = localFont({
  src: [
    {
      path: "../../public/fonts/PlayFairDisplay/PlayfairDisplay-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/PlayFairDisplay/PlayfairDisplay-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/fonts/PlayFairDisplay/PlayfairDisplay-SemiBold.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../../public/fonts/PlayFairDisplay/PlayfairDisplay-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-playfair",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${raleway.variable} ${playfairDisplay.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <SmoothScroll>
          <Providers>
            <Header />
            {children}
            <Footer />
          </Providers>
        </SmoothScroll>
      </body>
    </html>
  );
}
