import "./globals.css";
import localFont from "next/font/local";
import Providers from "./Provider";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";
import AppContent from "@/component/AppContent";

const raleway = localFont({
  src: [
    { path: "../../public/fonts/Railway/Raleway-Light.ttf", weight: "300", style: "normal" },
    { path: "../../public/fonts/Railway/Raleway-Regular.ttf", weight: "400", style: "normal" },
    { path: "../../public/fonts/Railway/Raleway-Medium.ttf", weight: "500", style: "normal" },
    { path: "../../public/fonts/Railway/Raleway-SemiBold.ttf", weight: "600", style: "normal" },
    { path: "../../public/fonts/Railway/Raleway-Bold.ttf", weight: "700", style: "normal" },
  ],
  variable: "--font-raleway",
});

const playfairDisplay = localFont({
  src: [
    { path: "../../public/fonts/PlayFairDisplay/PlayfairDisplay-Regular.ttf", weight: "400", style: "normal" },
    { path: "../../public/fonts/PlayFairDisplay/PlayfairDisplay-Medium.ttf", weight: "500", style: "normal" },
    { path: "../../public/fonts/PlayFairDisplay/PlayfairDisplay-SemiBold.ttf", weight: "600", style: "normal" },
    { path: "../../public/fonts/PlayFairDisplay/PlayfairDisplay-Bold.ttf", weight: "700", style: "normal" },
  ],
  variable: "--font-playfair",
});

export const metadata = {
  title: "Admin Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${raleway.variable} ${playfairDisplay.variable} h-full antialiased`}
    >
      <body className="min-h-screen bg-gray-50">
        <Providers>
          {/* AppContent तय करेगा कि Sidebar दिखाना है या सिर्फ Login */}
          <AppContent>{children}</AppContent>
          <ToastContainer position="bottom-right" autoClose={3000} />
        </Providers>
      </body>
    </html>
  );
}